name: ds_loyalty_user
description: DS Loyalty member application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3+3

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  firebase_core: 0.5.2
  firebase_auth: 0.18.2
  google_sign_in: 4.5.6
  flutter_facebook_auth: ^1.0.0
  qr_flutter: ^4.0.0
  provider: 4.3.2+2
  google_fonts: 1.1.2
  cloud_firestore: 0.14.3
  flutter_barcode_scanner: ^2.0.0
  flutter_slidable: ^0.6.0
  flutter_launcher_icons: ^0.9.0
  numberpicker: ^2.1.1
  url_launcher: ^6.0.4



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - fonts/